import { EventSummary } from '../Model/eventSummay';


export class EventSummaryData {
    static eventsSummary: EventSummary[] = [
        {
            id: 'EVNT00047261',
            month: 'DEC',
            baseLocation: 'Singapore',
            beneficiaryName: 'KWONG WAI SHIU HOSPITAL',
            venueAddress: '705, Serangoon Road, Singapore, Singapore, Singapore-328127',
            councilName: 'Outreach Singapore',
            project: 'Donation or Distribution',
            category: 'Essentials or relief',
            eventName: 'Bags of Joy Distribution',
            eventDescription: 'Thank you for all your donations of food items to make this a good Xmas for everyone! ',
            eventDate : '15-12-18',
            totalNoVolunteers: 21,
            totalVolunteHours: '88',
            totalTravelHours: '42',
            overallVolunteeringHours: '130',
            livesImpacted: 800,
            activityType: '1',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046103',
            month: 'DEC',
            baseLocation: 'Chennai',
            beneficiaryName: 'Kamarajar Illam,Tambaram',
            venueAddress: 'Gandhi Rd, Ranganathapuram, Tambaram, Tambaram, , , India-600045',
            councilName: 'Chennai BFS Outreach',
            project: 'Be a Teacher',
            category: 'Multiple Subjects',
            eventName: 'Be a Teacher @ Kamarajar Illam',
            eventDescription: 'Teach various subjects to the students in Kamarajar Illam',
            eventDate : '01-12-18',
            totalNoVolunteers: 14,
            totalVolunteHours: '28',
            totalTravelHours: '14',
            overallVolunteeringHours: '42',
            livesImpacted: 30,
            activityType: '3',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046385',
            month: 'DEC',
            baseLocation: 'United Kingdom',
            beneficiaryName: 'St. Edward’s CE Voluntary Aided Primary School',
            venueAddress: 'Havering Drive, Havering Drive, , , Romford-RM1 4BT',
            councilName: 'Outreach UK',
            project: 'Community Program',
            category: 'Other Community Programs',
            eventName: '1st Dec PM-Christmas fair to save a school swimming pool',
            eventDescription: 'The school is ho. ',
            eventDate : '01-12-18',
            totalNoVolunteers: 4,
            totalVolunteHours: '24',
            totalTravelHours: '0',
            overallVolunteeringHours: '24',
            livesImpacted: 0,
            activityType: '3',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046530',
            month: 'DEC',
            baseLocation: 'Pune',
            beneficiaryName: 'Gurukulam',
            venueAddress: 'Krantiveer Chapekar Smarak Samitee, Opposite Ram Mandir, Chinchwad Gaon, Pune, Maharashtra, India-411033',
            councilName: 'Pune QEA LBG Outreach',
            project: 'Be a Teacher',
            category: 'Other Subject',
            eventName: 'Improve in Co-ordination',
            eventDescription: 'There is a lack of co-ordination in between the students and no friendly relation to each other.  s.',
            eventDate : '01-12-18',
            totalNoVolunteers: 2,
            totalVolunteHours: '5',
            totalTravelHours: '0',
            overallVolunteeringHours: '5',
            livesImpacted: 20,
            activityType: '4',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046531',
            month: 'DEC',
            baseLocation: 'Pune',
            beneficiaryName: 'Gurukulam',
            venueAddress: 'Krantiveer Chapekar Smarak Samitee, Opposite Ram Mandir, Chinchwad Gaon, Pune, Maharashtra, India-411033',
            councilName: 'Pune QEA LBG Outreach',
            project: 'Be a Teacher',
            category: 'Other Subject',
            eventName: 'Improve in Co-ordination',
            eventDescription: 'There is a lack of co-ordination in between the students and no friendly relation to each other. .',
            eventDate : '08-12-18',
            totalNoVolunteers: 2,
            totalVolunteHours: '4',
            totalTravelHours: '0',
            overallVolunteeringHours: '4',
            livesImpacted: 2,
            activityType: '4',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046588',
            month: 'DEC',
            baseLocation: 'Chennai',
            beneficiaryName: 'ADW Primary school chitlapakkam',
            venueAddress: 'Chitlapakkam, , , India-600064',
            councilName: 'Chennai BPS Outreach',
            project: 'Be a Teacher',
            category: 'English',
            eventName: 'BAT',
            eventDescription: 'BAT',
            eventDate : '03-12-18',
            totalNoVolunteers: 2,
            totalVolunteHours: '4',
            totalTravelHours: '0',
            overallVolunteeringHours: '4',
            livesImpacted: 2,
            activityType: '4',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00046611',
            month: 'DEC',
            baseLocation: 'Coimbatore',
            beneficiaryName: 'Panchayat Union Primary School, Keeranatham Puthupalayam',
            venueAddress: 'Keeranatham Puthupalayam, Coimbatore, Tamil nadu, India-641035',
            councilName: 'Coimbatore Outreach',
            project: 'Be a Teacher',
            category: 'Multiple Subjects',
            eventName: 'TEACHING',
            eventDescription: 'Teaches English Grammar',
            eventDate : '13-12-18',
            totalNoVolunteers: 5,
            totalVolunteHours: '10',
            totalTravelHours: '2.5',
            overallVolunteeringHours: '12.5',
            livesImpacted: 22,
            activityType: '3',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        },
        {
            id: 'EVNT00047114',
            month: 'DEC',
            baseLocation: 'Chennai',
            beneficiaryName: 'Panchayat Union Primary School, Amman Nagar',
            venueAddress: 'Amman Nagar, Trisulam, Chennai, Tamil Nadu, India-600043',
            councilName: 'Chennai RCG Outreach',
            project: 'Be a Teacher',
            category: 'English',
            eventName: 'Be a Teacher',
            eventDescription: 'Category students of 4th std students (A and B section).',
            eventDate : '04-12-18',
            totalNoVolunteers: 6,
            totalVolunteHours: '0.6',
            totalTravelHours: '9',
            overallVolunteeringHours: '9.6',
            livesImpacted: 1,
            activityType: '5',
            status: 'Approved',
            pocID: '632416',
            pocName: 'Name1',
            pocContactNumber: '9962294222'
        }
    ];
}
